import org.apache.dubbo.config.spring.beans.factory.config.DubboConfigDefaultPropertyValueBeanPostProcessor;
public class FunctionUse848 {
public void funcUse() {
DubboConfigDefaultPropertyValueBeanPostProcessor dubboconfigdefaultpropertyvaluebeanpostprocessor = new DubboConfigDefaultPropertyValueBeanPostProcessor();
dubboconfigdefaultpropertyvaluebeanpostprocessor.processBeforeInitialization(null,null);
}
}